import React from "react";
import "../globals.css";

import Sidebar from "@/components/Sidebar";

export const metadata = {
  title: "CLC - Children Learning Center",
  description: "Generated by SweatBox app",
};

const LayoutPage = ({ children }) => {
  return (
    <div className="flex overflow-auto max-h-screen">
      <Sidebar />

      <div className="w-full h-screen rounded-lg overflow-auto bg-slate-100">
        {children}
      </div>
    </div>
  );
};

export default LayoutPage;
