import React from "react";
import "../../../globals.css";

export const metadata = {
  title: "CLC - Children Learning Center",
  description: "Generated by SweatBox app",
};

const LayoutRaporPage = ({ children }) => {
  return (
    <div className="w-full min-h-screen rounded-lg overflow-auto bg-slate-100 pb-10">
      {children}
    </div>
  );
};

export default LayoutRaporPage;
